services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: backend_cs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - backend_cs_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d backend_cs"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ..                        # RAÍZ del repo (donde están todas las carpetas backend_cs.*)
      dockerfile: Api/Api.Dockerfile
    environment:
      # .NET 8+ soporta ASPNETCORE_HTTP_PORTS como alternativa simple.
      ASPNETCORE_HTTP_PORTS: "8080"   # o usa ASPNETCORE_URLS si prefieres
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Default: "Host=db;Port=5432;Database=backend_cs;Username=postgres;Password=postgres"
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: backend_cs-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  backend_cs_data:
